[build]
  publish = "/"
  command = ""  # No build command needed for static HTML site

# Configure trailing slash handling
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Handle success page redirect
[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

# Asset optimization
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

# Headers to improve security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://cdnjs.cloudflare.com https://fonts.googleapis.com https://fonts.gstatic.com https://i.imgur.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com; script-src 'self' 'unsafe-inline';"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache control for static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Define basic auth for staging/preview branches (optional)
# Uncomment if you want to password-protect non-production deployments
# [[plugins]]
#   package = "netlify-plugin-http-auth"
#   [plugins.inputs]
#   username = "preview"
#   password = "paisatrack" 